### ISSUE TITLE
Segmentation faul (core dumped)

### ISSUE THREAD

**Issue by ssholm** [mbyrdal/p1_administration_i_foreninger#1]
**Følgende udveksling med programmet fandt sted: **
\> a
Mappe fundet!
Hvad vil du nu?

1.  Aabne en fil (Laese fra fil)
2.  Oprette en ny fil (Skrive til fil)
\> 1
Skriv navn paa filen
\> q
Fil ikke fundet. Vil du oprette en ny fil med dette navn? [ja/nej]
\> ja
Segmentation fault (core dumped)

**Comment by ssholm** [comment]
Jeg kan se, at det går galt i `start_prompt.c` på linje 85 -104. Uanset om filen findes eller ej kaldes `fclose()`, og det kan den vel ikke, når ikke filen findes.
Derudover tjekkes der ikke, om brugeren vil oprette en fil i `else` delen af `if`-statementet.

**Comment by mourits324** [comment]
Er vel ordnet? Jeg kan i hvert fald ikke få fejlen længere
