### ISSUE TITLE
Overskriver eksisterende fil

### ISSUE THREAD

**Issue by ssholm** [mbyrdal/p1_administration_i_foreninger#2]
**Følgende udveksling fandt sted (filen 3.txt findes):**
[Fejl_overskrivning_af_fil.txt](https://github.com/mbyrdal/p1_administration_i_foreninger/files/3945925/Fejl_overskrivning_af_fil.txt)

**Comment by mourits324** [comment]
Er det en fejl at den overskriver der? Du beder den jo om at skrive til filen og ikke læse fra den?

**Comment by DVH-H** [comment]
Vi kan slette opret ny fil, for åben fil opretter alligevel filen hvis den ikke eksistere. 
Og så bare ændre printf'en til at sige "Åben fil eller opret ny fil"
