### ISSUE TITLE
Opret mappe

### ISSUE THREAD

**Issue by mourits324** [mbyrdal/p1_administration_i_foreninger#20]
Hvis man taster nej til at oprette en mappe oprettes den alligevel og man kommer ud af loopet

**Comment by ssholm** [comment]
Ved mig oprettes mappen ikke alligvel, men jeg kan kun komme ud af loopet ved at oprette mappen. Prøv at git pull igen. Vi har lavet nogle ændringer allerede :D

**Comment by mourits324** [comment]
Ookay ordnet
