### ISSUE TITLE
Mappe oprettes, selvom at der skrives "nej" til oprettelse af en mappe

### ISSUE THREAD

**Issue by mbyrdal** [mbyrdal/p1_administration_i_foreninger#4]
[Opretter_mappe_ved_input_nej.txt](https://github.com/mbyrdal/p1_administration_i_foreninger/files/3950310/Opretter_mappe_ved_input_nej.txt)

**Comment by Jako4458** [comment]
i Start_prompt.c er der generelt byttet om på [j/n]
