### ISSUE TITLE
Fanget i loop ved oprettelse af opgave

### ISSUE THREAD

**Issue by mbyrdal** [mbyrdal/p1_administration_i_foreninger#9]
[Endless_loop_ved_oprettelse_af_opgave.txt](https://github.com/mbyrdal/p1_administration_i_foreninger/files/3950342/Endless_loop_ved_oprettelse_af_opgave.txt)

**Comment by mourits324** [comment]
Yup, forventeligt ved deadline, da jeg ikke aner hvordan man clear den. Måske med clear_input(), men har ikke testet det
